# Generated by Django 6.0.5 on 2026-06-16 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterField(
            model_name='order',
            name='business_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_business', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_customer', to=settings.AUTH_USER_MODEL),
        ),
    ]
