# Generated by Django 6.0.5 on 2026-06-16 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0002_alter_offer_options_alter_offer_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Offer', 'verbose_name_plural': 'Offers'},
        ),
    ]
