# Generated by Django 6.0.5 on 2026-06-16 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0003_alter_offer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offerdetail',
            options={'verbose_name': 'Offer Detail', 'verbose_name_plural': 'Offer Details'},
        ),
    ]
