# Generated by Django 6.0.5 on 2026-06-05 08:43

import profile_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_profile_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=profile_app.models.user_profile_path),
        ),
    ]
