# Generated by Django 6.0.5 on 2026-06-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0004_alter_profile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
